### ISSUE TITLE
Currency dropdown onChange event does not immediately update value of holdings

### ISSUE THREAD

**Issue by sinisbad123** [ed3ath/cbtracker#10]
Steps to reproduce:

1. Add an account to track
2. Wait for information to load
3. Change the currency dropdown to any other currency
4. See the bug

Suggestion: Probably we can preload the current rates of different currencies upon page load, that way, we can prevent request loading times whenever the dropdown value changes.

**Comment by ed3ath** [comment]
fixed 

https://github.com/ed3ath/cbtracker/commit/1da12fcac7fe18d82b5587c034709edb7fcbf4eb
