### ISSUE TITLE
Error Deploy to Heroku

### ISSUE THREAD

**Issue by alteregog1** [ed3ath/cbtracker#12]
hi i have this error when deploy it to heroku

`at=error code=H10 desc="App crashed" method=GET path="/" host=cbtracker-id.herokuapp.com request_id=f31fdb54-5625-4924-971e-4f8aefccbd2d fwd="103.107.198.116" dyno= connect= service= status=503 bytes= protocol=https
at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cbtracker-id.herokuapp.com request_id=f3394497-c401-43d1-88ac-0401ebf8fce2 fwd="103.107.198.116" dyno= connect= service= status=503 bytes= protocol=https
`

**Comment by alguintu** [comment]
getting the same error. how to fix?

**Comment by ed3ath** [comment]
try to set the NODE_ENV to development

**Comment by nethzsumang** [comment]
I have solved this problem.
Aside from setting the NODE_ENV to development, edit the following code:
`const httpPort = process.env.HTTP_PORT || process.env.PORT || 3000;`
Then push and re-deploy the app.
