### ISSUE TITLE
Suggestion: Best Weapon

### ISSUE THREAD

**Issue by Mushbee** [ed3ath/cbtracker#16]
Hi, first great project!

My suggestion is to show on the combat simulator the weapon/enemy with higher winning chances.

**Comment by Vinhuit** [comment]
yes, should be show 3 4 suggestion follow order priority like "winning chances" --> reward.

**Comment by Enddox** [comment]
> Hi, first great project!
> 
> My suggestion is to show on the combat simulator the weapon/enemy with higher winning chances.

to do this the site needs to run a combat with every character with every sword everytime you click combat simulator button, its possible but its bad for the site performance, huge lag when clicking combat simulator button.

**Comment by ed3ath** [comment]
> > Hi, first great project!
> > My suggestion is to show on the combat simulator the weapon/enemy with higher winning chances.
> 
> to do this the site needs to run a combat with every character with every sword everytime you click combat simulator button, its possible but its bad for the site performance, huge lag when clicking combat simulator button.

agree. especially with accounts having 100+ weapons
