### ISSUE TITLE
Suggestion: include claim taxes on total skill assets calculations

### ISSUE THREAD

**Issue by rodipm** [ed3ath/cbtracker#18]
Hi, very helpful project. Keep going!

Wouldn't it be interesting to add current claim taxes on total skill assets for a more accurate daily value projection?

**Comment by rodipm** [comment]
I think you could get claim tax with these code snippets:

library.js:
```
const getOwnRewardsClaimTax = address => conCryptoBlades.methods.getOwnRewardsClaimTax().call({ from: address });
```
core.js:
```
const claimTax = await getOwnRewardsClaimTax(address);
const unclaimedTaxed = unclaimed*(1-convertClaimTax(claimTax))
function convertClaimTax(value) {
    return value*0.15/2767011611056432742
}
```

**Comment by ed3ath** [comment]
can you make a PR?

**Comment by rodipm** [comment]
Yes, for sure.

Not sure if I came up with the best UI for it, but here it is. #29

**Comment by ed3ath** [comment]
merged
