### ISSUE TITLE
Suggestion: Browser extension

### ISSUE THREAD

**Issue by pawelpewq** [ed3ath/cbtracker#19]
I have a suggestion that you create a Browser Extension that will display the probability of winning a fight in Cryptoblades :) Someone has already done it, but I am afraid to install it because of the loss of funds from my Metamask. I trust you :)

![23123](https://user-images.githubusercontent.com/43301854/127734931-b09c9fcc-6154-4ef6-903c-4b83d8ff24c8.png)

**Comment by jepoy11** [comment]
Here is a legit one

https://github.com/coderaven/coderaven-cryptoblades-battle-simulator

**Comment by pawelpewq** [comment]
Each time this calculation from this plugin is run, it shows a different % for winning :| a bit strange.

**Comment by pawelpewq** [comment]
> Here is a legit one
> 
> https://github.com/coderaven/coderaven-cryptoblades-battle-simulator

Each time this calculation from this plugin is run, it shows a different % for winning :| a bit strange.

**Comment by jepoy11** [comment]
> > Here is a legit one
> > https://github.com/coderaven/coderaven-cryptoblades-battle-simulator
> 
> Each time this calculation from this plugin is run, it shows a different % for winning :| a bit strange.

Thats true. This is because of the +/-10% tolerance in the formula declared in the cb wiki. The extension compute 100x to get the % using random tolerance within +/-10%

**Comment by Enddox** [comment]
> Here is a legit one
> 
> https://github.com/coderaven/coderaven-cryptoblades-battle-simulator

I want an extension made by ed3ath, not someone else.

**Comment by ed3ath** [comment]
I will try making one
