### ISSUE TITLE
How do I start it on my PC?

### ISSUE THREAD

**Issue by just2102** [ed3ath/cbtracker#20]
I know no programming at all, how do I start this on my pc? The web version seems to be unstable sometimes. Thanks in advance.

**Comment by ranjim** [comment]
Guide here: https://gadgetpilipinas.net/2021/07/cryptoblades-how-to-easily-track-character-stamina-and-xp-gain/

**Comment by just2102** [comment]
> Guide here: https://gadgetpilipinas.net/2021/07/cryptoblades-how-to-easily-track-character-stamina-and-xp-gain/

thank you, but I can't seem to get it running. I get this error when I type "npm install": 
bash: npm: command not found

**Comment by gianviterbo** [comment]
> > Guide here: https://gadgetpilipinas.net/2021/07/cryptoblades-how-to-easily-track-character-stamina-and-xp-gain/
> 
> thank you, but I can't seem to get it running. I get this error when I type "npm install":
> bash: npm: command not found

Hello! Be sure to get execute that command inside the cbtracker folder. if it fails, you may also want to try this command below:

`$ npm install -g bower`

**Comment by ranjim** [comment]
> > > Guide here: https://gadgetpilipinas.net/2021/07/cryptoblades-how-to-easily-track-character-stamina-and-xp-gain/
> > 
> > 
> > thank you, but I can't seem to get it running. I get this error when I type "npm install":
> > bash: npm: command not found
> 
> Hello! Be sure to get execute that command inside the cbtracker folder.

thank you for the guide! replies seemed to be off on your blog :)
