### ISSUE TITLE
ARS price is wrong.

### ISSUE THREAD

**Issue by facusr** [ed3ath/cbtracker#24]
Hi, when you put ARS as the currency to show the balance, it shows it with an unreal conversion. In Argentina you have price for Usd official and Unofficial USD (USD BLUE). Argentinian people can only access USD BLUE (unofficial one). Please use the USD BLUE conversion from https://www.ambito.com/contenidos/dolar-informal.html
Thanks and sorry for bothering.

**Comment by ed3ath** [comment]
The fiat conversion is based from coingecko. https://api.coingecko.com/api/v3/simple/price?ids=cryptoblades,tether&vs_currencies=ars

**Comment by ed3ath** [comment]
> Hi, when you put ARS as the currency to show the balance, it shows it with an unreal conversion. In Argentina you have price for Usd official and Unofficial USD (USD BLUE). Argentinian people can only access USD BLUE (unofficial one). Please use the USD BLUE conversion from https://www.ambito.com/contenidos/dolar-informal.html
> Thanks and sorry for bothering.

can you provide an api for this? sorry I can't understand spanish.

**Comment by jlgasparrini** [comment]
ARS conversion is working right, dismiss and close this issue. Is wrong to use another ARS rate conversion.

@facusr they are using the official rate conversion provided for our [Argentinian Central Bank](http://www.bcra.gov.ar/).
Unofficial rate conversions like USD BLUE are illegal and there is no API or service that provides information about those conversion rates.

**Comment by facusr** [comment]
> ARS conversion is working right, dismiss and close this issue. Is wrong to use another ARS rate conversion.
> 
> @facusr they are using the official rate conversion provided for our [Argentinian Central Bank](http://www.bcra.gov.ar/).
> Unofficial rate conversions like USD BLUE are illegal and there is no API or service that provides information about those conversion rates.

?? Nobody on Argentina can buy USD at official rate. Fucking peronists ruining everything. Why dont u go suck on alberto´s balls u dumb socialist. USD blue is THE ONLY rate that every Argentinian can access. Literally no one can buy at official rate, so there is no point for even keeping it on cbtracker.

**Comment by jlgasparrini** [comment]
> > ARS conversion is working right, dismiss and close this issue. Is wrong to use another ARS rate conversion.
> > @facusr they are using the official rate conversion provided for our [Argentinian Central Bank](http://www.bcra.gov.ar/).
> > Unofficial rate conversions like USD BLUE are illegal and there is no API or service that provides information about those conversion rates.
> 
> ?? Nobody on Argentina can buy USD at official rate. Fucking peronists ruining everything. Why dont u go suck on alberto´s balls u dumb socialist. USD blue is THE ONLY rate that every Argentinian can access. Literally no one can buy at official rate, so there is no point in even keeping it on cbtracker.

Language man! don't be disrespectful.... Of course, I don't support this government but this is no place to talk about that...

Let me explain something, you don't have access to USD money to the official rate? sure, nobody has access, but this is not cbtracker fault bro! Supplies, products, services, cereal, meat, etc are imported and exported at the official rate, that it! internationally you buy at the official bank rate, paying taxes is not part of the conversion rate...

What's wrong with you man? Put the hate aside and vote better next time. Do better research before speaking!
