### ISSUE TITLE
Suggestion: Initiate fight option in combat calculator

### ISSUE THREAD

**Issue by jericopulvera** [ed3ath/cbtracker#25]
I make mistakes in choosing characters and enemies in the cryptoblades app after doing a combat calculation in cbtracker.

It would be nice if we can initiate the fight in the cbtracker directly.

**Comment by ed3ath** [comment]
I can't do that since it's already an automation or bot. CB Devs won't allow it.

**Comment by jericopulvera** [comment]
> I can't do that since it's already an automation or bot. CB Devs won't allow it.

Too bad. Where did they say they don't allow it?

**Comment by ed3ath** [comment]
round table discussion
