### ISSUE TITLE
Battle calculations are wrong

### ISSUE THREAD

**Issue by hugoguercio** [ed3ath/cbtracker#26]
The battle calculations are wrong, probably not taking into account the elements properly.

![image](https://user-images.githubusercontent.com/10049675/127745616-002bea14-6ed6-4ef9-b4e7-0372de773d6a.png)

It says the chances are higher with same monster power but one of them is of weak element !

**Comment by ed3ath** [comment]
chance percentage is based on the min/max power of the enemy compared to yours (already with the element bonus)

please refer to the official formula https://github.com/CryptoBlades/cryptoblades/blob/c80a2215dce034b8356a3e0a7bc9105ded259a6a/frontend/src/views/Combat.vue#L227

**Comment by ed3ath** [comment]
I have merged your PR.

**Comment by arvi0731** [comment]
> I have merged your PR.

Thanks
