### ISSUE TITLE
Suggestion: Sorting per column

### ISSUE THREAD

**Issue by ranjsebs** [ed3ath/cbtracker#28]
Dunno if this is possible but would be a great quality of life improvement to sort most of the columns like stamina and unstake time, etc. Not sure how it would go if some teams are composed of different elements, though.

**Comment by Enddox** [comment]
> Dunno if this is possible but would be a great quality of life improvement to sort most of the columns like stamina and unstake time, etc. Not sure how it would go if some teams are composed of different elements, though.

not necessary

**Comment by ranjsebs** [comment]
> > Dunno if this is possible but would be a great quality of life improvement to sort most of the columns like stamina and unstake time, etc. Not sure how it would go if some teams are composed of different elements, though.
> 
> not necessary

could be very helpful for those with 20 accounts and above

**Comment by ed3ath** [comment]
it's kinda hard to sort the table because of merge cells

**Comment by ranjsebs** [comment]
> it's kinda hard to sort the table because of merge cells

understood. excited for the other premium futures soon :)
