### ISSUE TITLE
unable to lunch docker-compose up

### ISSUE THREAD

**Issue by kmacute** [ed3ath/cbtracker#3]
![image](https://user-images.githubusercontent.com/48196638/127352560-cd7e7aa6-f54d-405d-a83a-50f3f83effbe.png)

the error is just like this
![image](https://user-images.githubusercontent.com/48196638/127352641-c10a217c-b2fa-49e0-973f-be6499d8b0a1.png)

**Comment by ed3ath** [comment]
install v16 of node js
