### ISSUE TITLE
Suggestion: Stamina reminder

### ISSUE THREAD

**Issue by myrmidane** [ed3ath/cbtracker#31]
Hello man! Huge fan of your work right here! First of all I wanna thank you for making such a wonderful tool available for free, hopefully I can give back once I start earning from my battles. Now, I'd like to request a stamina reminder via email if possible. Like I set a reminder when a certain character linked via an account added reaches a certain stamina (e.g. 160) and it sends me an email. Hope this is possible so we don't have to calculate when to fight each time. Thank you bro.

**Comment by jepoy11** [comment]
Hello,

I made a simple tool to remind me via email using google sheet when target stamina reached. 
https://github.com/jepoy11/CryptoBlades-Stamina-Reminder/blob/e4405f584681d31e41794cc659bba65d4c5ef35d/README.md

**Comment by ed3ath** [comment]
> Hello man! Huge fan of your work right here! First of all I wanna thank you for making such a wonderful tool available for free, hopefully I can give back once I start earning from my battles. Now, I'd like to request a stamina reminder via email if possible. Like I set a reminder when a certain character linked via an account added reaches a certain stamina (e.g. 160) and it sends me an email. Hope this is possible so we don't have to calculate when to fight each time. Thank you bro.

I will add that feature on paid version which require subscription since free SMTP servers are only allowing 100 emails a day. With current average of 3000 daily users, 100 emails/day isn't enough.
