### ISSUE TITLE
Add VES Fiat

### ISSUE THREAD

**Issue by Enddox** [ed3ath/cbtracker#32]
VES Fiat is the Fiat from Venezuela.

The best way to add this is from the API of Dolartoday
[https://s3.amazonaws.com/dolartoday/data.json](https://s3.amazonaws.com/dolartoday/data.json)

The current dollar price is in Line 32 and all you need to do is a math "USD.transferencia * currentSkillPriceInUSD"

Please @ed3ath answer if you are not gonna add this Fiat and why.

**Comment by ed3ath** [comment]
added https://github.com/ed3ath/cbtracker/commit/479665beb5d2860f6b043b13549a47a1bc0d57fd
