### ISSUE TITLE
Bug: Claim now is not working properly!

### ISSUE THREAD

**Issue by jlgasparrini** [ed3ath/cbtracker#36]
First of all, I want to give my thanks for this amazing job that you have done. Good job guys.

I've some wrong calculations that I want to report!. Today I saw the suggestion label "Claim now" on one of my characters to advance to level 31, but after claim XP rewards the same character didn't reach level 31.

I attached an image of my current XP on the character that already mentions before.
![image](https://user-images.githubusercontent.com/4787484/127788433-271cdd08-4a16-49de-bf21-862bdd1f4c43.png)

**Comment by ed3ath** [comment]
there's delay with the claim transaction and retrieving the data. try to refresh again after 1 min
