### ISSUE TITLE
Sorry, when I donated  money I entered the excessive amount of by mistake...

### ISSUE THREAD

**Issue by oopsjay** [ed3ath/cbtracker#51]
I was about to donate 0.66 skill, but I  typed 2.66 by mistake.
I am so sorry for that, could you please refund 2 skill to the sender's address?

The tx here:
https://bscscan.com/tx/0xb462bf10f7904715f805f68c8d21c8f1b1fac905d07459d21d707b4f3ab0aab2

**Comment by ed3ath** [comment]
refunded
