### ISSUE TITLE
Request: Remove or add option to disable In-Game SKILL tracking

### ISSUE THREAD

**Issue by Dannii-Darkness** [ed3ath/cbtracker#53]
Remove In-Game Skill or at least add a button to disable it. As far as I am aware there is no way to earn In-Game SKILL anymore so I imagine for most people who have already spent their In-Game SKILL this is just throwing their total SKILL asset figures out.

Thanks. Love the tracker.

**Comment by ed3ath** [comment]
IGO SKILLs are not included in the total SKILL assets.
