### ISSUE TITLE
Invitation

### ISSUE THREAD

**Issue by osodatsismoso** [ed3ath/cbtracker#56]
Hi ed3ath,

We are part of a small community that aims to better understand CryptoCurrency. Our topic Focusing on CryptoBlades, in our country it is one of the most trending games Play to Earn Category close to Axie Infinity. 
Sorry for using this section. I am new to GitHub and trying to get in touch with you. This is the closest I can get.
I want to immerse my countrymen with your bright ideas and perception of why you have come up with this wonderful and powerful Tool. Hope to get in touch with you. Here is our email OsoTsismoso@gmail.com 

Best Regards, 
Oso Bear

**Comment by ed3ath** [comment]
I just want to manage and monitor my accounts easily so I made this tool.

**Comment by osodatsismoso** [comment]
Greetings,

It is such an honor to get a response from you, despite how busy you are
with all the inquiries and the success of your tool.
I would like to ask if you are okay with a small and informal interview
about your tool and the noble act you did for this product.
My countrymen will really appreciate it and we've been expecting your
response and will be more patient for another.
Just a zoom interview 3-5mins 3 questions that would be great.

sincerely,
Oso Bear

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
